instrumentation:
  root: src
  default-excludes: true
  excludes:
    - 'assets/**'
    - 'build/**'
  embed-source: false
  complete-copy: false
  include-all-sources: true
reporting:
  print: summary
  reports:
    - lcov
  dir: ./build/coverage
  watermarks:
    statements: [80, 100]
    lines: [80, 100]
    functions: [80, 100]
    branches: [80, 100]
check:
  global:
    statements: 80
    lines: 80
    branches: 80
    functions: 80
    excludes: []
