instrumentation:
  root: .
  default-excludes: true
  excludes:
    - 'build/**'
    - 'webpack.config.js'
  embed-source: false
  complete-copy: false
  include-all-sources: true
reporting:
  print: summary
  reports:
    - lcov
  dir: ./build/coverage
  watermarks:
    statements: [99, 100]
    lines: [99, 100]
    functions: [99, 100]
    branches: [99, 100]
check:
  global:
    statements: 100
    lines: 100
    branches: 100
    functions: 100
    excludes: []
